set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN H16 [get_ports sys_clk]
set_property PACKAGE_PIN G14 [get_ports led]
set_property PACKAGE_PIN R19 [get_ports rst_n]