# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ada_hdmi/ada_hdmi.srcs/sources_1/ip/rom8_1024/rom8_1024.xci
# IP: The module: 'rom8_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ada_hdmi/ada_hdmi.srcs/sources_1/ip/rom8_1024/rom8_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom8_1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ada_hdmi/ada_hdmi.srcs/sources_1/ip/rom8_1024/rom8_1024.xci
# IP: The module: 'rom8_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ada_hdmi/ada_hdmi.srcs/sources_1/ip/rom8_1024/rom8_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom8_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
