# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/hdmi_photo/hdmi_photo.srcs/sources_1/ip/rom_image/rom_image.xci
# IP: The module: 'rom_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/hdmi_photo/hdmi_photo.srcs/sources_1/ip/rom_image/rom_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_image'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/hdmi_photo/hdmi_photo.srcs/sources_1/ip/rom_image/rom_image.xci
# IP: The module: 'rom_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/hdmi_photo/hdmi_photo.srcs/sources_1/ip/rom_image/rom_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
