######################################################################
#
# File name : tb_pll_led_compile.do
# Created on: Fri Jan 21 19:01:51 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../PLL.srcs/sources_1/ip/clock" \
"../../../../PLL.srcs/sources_1/ip/clock/clock_clk_wiz.v" \
"../../../../PLL.srcs/sources_1/ip/clock/clock.v" \
"../../../../PLL.srcs/sources_1/new/pll_test.v" \
"../../../../PLL.srcs/sim_1/new/tb_pll.v" \


# compile glbl module
C:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

