# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lenovo/Desktop/CICC/CICC/CICC.srcs/sources_1/ip/I2S_fifo/I2S_fifo.xci
# IP: The module: 'I2S_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Desktop/CICC/CICC/CICC.srcs/sources_1/ip/I2S_fifo/I2S_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2S_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lenovo/Desktop/CICC/CICC/CICC.srcs/sources_1/ip/I2S_fifo/I2S_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2S_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/lenovo/Desktop/CICC/CICC/CICC.srcs/sources_1/ip/I2S_fifo/I2S_fifo.xci
# IP: The module: 'I2S_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Desktop/CICC/CICC/CICC.srcs/sources_1/ip/I2S_fifo/I2S_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2S_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lenovo/Desktop/CICC/CICC/CICC.srcs/sources_1/ip/I2S_fifo/I2S_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2S_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
