# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8.xci
# IP: The module: 'fifo_wr256_8_rd256_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8.xci
# IP: The module: 'fifo_wr256_8_rd256_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/FIFO/FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/fifo_wr256_8_rd256_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
