# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/predeal_0.xci
# IP: The module: 'predeal_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/predeal_fir_compiler_v7_2_i0/predeal_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==predeal_fir_compiler_v7_2_i0 || ORIG_REF_NAME==predeal_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/predeal_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==predeal_fir_compiler_v7_2_i0 || ORIG_REF_NAME==predeal_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/constrs/predeal.xdc
# XDC: The top module name and the constraint reference have the same name: 'predeal_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/predeal_0.xci
# IP: The module: 'predeal_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/predeal_fir_compiler_v7_2_i0/predeal_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==predeal_fir_compiler_v7_2_i0 || ORIG_REF_NAME==predeal_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/predeal_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==predeal_fir_compiler_v7_2_i0 || ORIG_REF_NAME==predeal_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/lenovo/Desktop/CICC/filter1/ip_catalog/predeal.srcs/sources_1/ip/predeal_0/constrs/predeal.xdc
# XDC: The top module name and the constraint reference have the same name: 'predeal_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
