######################################################################
#
# File name : tb_ram_pp_wave.do
# Created on: Sat Jan 22 12:04:07 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
