######################################################################
#
# File name : tb_ram_pp_compile.do
# Created on: Sun Jan 23 19:15:23 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../ram_pp.srcs/sources_1/ip/ram_wr256_8_rd256_8/sim/ram_wr256_8_rd256_8.v" \
"../../../../ram_pp.srcs/sources_1/new/ram_pp.v" \
"../../../../ram_pp.srcs/sim_1/new/tb_ram_pp.v" \


# compile glbl module
C:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

