# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/rom_sin_1024_8/rom_sin_1024_8.xci
# IP: The module: 'rom_sin_1024_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/rom_sin_1024_8/rom_sin_1024_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sin_1024_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/rom_sin_1024_8/rom_sin_1024_8.xci
# IP: The module: 'rom_sin_1024_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/rom_sin_1024_8/rom_sin_1024_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sin_1024_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
