######################################################################
#
# File name : tb_fifo_test_compile.do
# Created on: Thu Jan 27 18:56:31 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../FIFO.srcs/sources_1/ip/fifo_wr256_8_rd256_8/sim/fifo_wr256_8_rd256_8.v" \
"../../../../FIFO.srcs/sources_1/new/fifo_test.v" \
"../../../../FIFO.srcs/sim_1/new/tb_fifo_test.v" \


# compile glbl module
C:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

