# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/dpram_8_1024/dpram_8_1024.xci
# IP: The module: 'dpram_8_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/dpram_8_1024/dpram_8_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_8_1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/dpram_8_1024/dpram_8_1024.xci
# IP: The module: 'dpram_8_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/vivado_project/adda_hdmi_final/adda_hdmi_final.srcs/sources_1/ip/dpram_8_1024/dpram_8_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_8_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
