# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ram_pp/ram_pp.srcs/sources_1/ip/ram_wr256_8_rd256_8/ram_wr256_8_rd256_8.xci
# IP: The module: 'ram_wr256_8_rd256_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ram_pp/ram_pp.srcs/sources_1/ip/ram_wr256_8_rd256_8/ram_wr256_8_rd256_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ram_pp/ram_pp.srcs/sources_1/ip/ram_wr256_8_rd256_8/ram_wr256_8_rd256_8.xci
# IP: The module: 'ram_wr256_8_rd256_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Raymond_Meng/Documents/xlinx_FPGA/vivado_projects/ram_pp/ram_pp.srcs/sources_1/ip/ram_wr256_8_rd256_8/ram_wr256_8_rd256_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_wr256_8_rd256_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
