######################################################################
#
# File name : pwm_led_sim_compile.do
# Created on: Thu Jan 20 22:13:24 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../pwm_led.srcs/sim_1/new/pwm_led_sim.v" \


# compile glbl module
C:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

