######################################################################
#
# File name : pwm_led_sim_simulate.do
# Created on: Thu Jan 20 22:13:30 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.pwm_led_sim xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {pwm_led_sim_wave.do}

view wave
view structure
view signals

do {pwm_led_sim.udo}

run 1000ns
