######################################################################
#
# File name : pwm_led_sim.udo
# Created on: Thu Jan 20 22:13:30 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
