######################################################################
#
# File name : pwm_led_sim_wave.do
# Created on: Thu Jan 20 22:13:30 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
