######################################################################
#
# File name : source_compile.do
# Created on: Sun Feb 20 23:56:07 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../IC_Competition_Design.srcs/sources_1/new/source.v" \


# compile glbl module
C:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

